language: java
sudo: true
jdk:
- oraclejdk8
script:
- mvn clean compile assembly:single

addons:
  ssh_known_hosts: simplysentient.com

before_install:
- bash _scripts/install.sh

after_success:
- scp -o StrictHostKeyChecking=no target/applicationServer-*.jar $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
