language: java
sudo: true
jdk:
- oraclejdk8
script:
- mvn clean compile assembly:single

addons:
  ssh_known_hosts: simplysentient.com

before_install:
- bash _scripts/install.sh

after_success:
- bash <(curl -s https://codecov.io/bash) -t e0e8c63b-befd-4c3f-8308-99e5352007a0
- scp -o StrictHostKeyChecking=no target/applicationServer-*.jar $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
