language: java
sudo: true
jdk:
- oraclejdk8
script:
- mvn clean compile assembly:single
- mvn cobertura:cobertura

addons:
  ssh_known_hosts: simplysentient.com

before_install:
- bash _scripts/install.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
#- scp -o StrictHostKeyChecking=no target/applicationServer-*.jar stuart@power-cloud.tech:/home/stuart/ApplicationServer
